DROP TABLE IF EXISTS `stock_stats`;
CREATE TABLE `stock_stats` ( -- QUANDL/DMDRN
	`symbol`		VARCHAR(6) NOT NULL,
	`quote_date`	DATE NOT NULL,
	`float`			FLOAT(8,2) NULL,
	`insider`		FLOAT(8,4) NULL,
	`capex`			INT(8) ,
	`net_marg`		FLOAT(12,8) NULL,
	`inv_cap`		INT(8) NULL,
	`p_s`			FLOAT(12,8) NULL,
	`roc`			FLOAT(12,8) NULL,
	`stock_px`		FLOAT(8,2) NULL,
	`mkt_de`		FLOAT(8,4) NULL,
	`correl`		FLOAT(8,4) NULL,
	`pe_fwd`		FLOAT(12,8) NULL,
	`rev_gro`		FLOAT(8,4) NULL,
	`ebit_1t`		FLOAT(12,4) NULL,
	`div`			FLOAT(10,2) NULL,
	`eps_fwd`		FLOAT(8,4) NULL,
	`chg_ncwc`		FLOAT(8,4) NULL, -- UNKN
	`cash_fv`		FLOAT(12,8) NULL,
	`inst_hold`		FLOAT(12,8) NULL,
	`eff_tax`		FLOAT(10,8) NULL,
	`cash_assets`	FLOAT(10,8) NULL,
	`fixed_tot`		FLOAT(10,8) NULL,
	`beta_vl`		FLOAT(4,2) NULL,
	`bv_assets`		INT(8) NULL,
	`bv_eqty`		INT(8) NULL,
	`fcff`			FLOAT(10,4) NULL,
	`cash_rev`		FLOAT(10,8) NULL,
	`mkt_cap`		FLOAT(10,2) NULL,
	`eff_tax_inc`	FLOAT(10,8) NULL,
	`ev_sales`		FLOAT(12,8) NULL,
	`tot_debt`		FLOAT(12,4) NULL, -- UNKN
	`intang_tot`	FLOAT(10,8) NULL, -- UNKN
	`pe_g`			FLOAT(10,8) NULL,
	`reinv_rate`	FLOAT(10,8) NULL,
	`book_dc`		FLOAT(10,8) NULL, -- UNKN
	`eps_gro_exp`	FLOAT(10,6) NULL,
	`ev_ebit`		FLOAT(12,8) NULL,
	`pe_curr`		FLOAT(12,8) NULL,
	`mkt_dc`		FLOAT(10,8) NULL, -- UNKN
	`ncwc_rev`		FLOAT(10,8) NULL,
	`rev_12m`		INT(8) NULL,
	`rev_gro_exp`	FLOAT(6,4) NULL,
	`rev_trail`		INT(8) NULL,
	`roe`			FLOAT(10,8) NULL,
	`ev_ebitda`		FLOAT(12,8) NULL,
	`ebitda`		INT(8) NULL,
	`beta`			FLOAT(6,4) NULL,
	`deprec`		INT(8) NULL,
	`ev_salestr`	FLOAT(12,8) NULL,
	`eps_gro`		FLOAT(12,4) NULL,
	`p_bv`			FLOAT(12,8) NULL,
	`net_inc_trail`	INT(8) NULL,
	`pe_trail`		FLOAT(12,8) NULL,
	`op_marg`		FLOAT(10,8) NULL,
	`firm_val`		FLOAT(10,2) NULL,
	`stdev`			FLOAT(6,4) NULL,
	`trad_vol`		INT(10) NULL,
	`cash`			INT(8) NULL,
	`div_yld`		FLOAT(6,4) NULL,
	`rev_last`		INT(8) NULL,
	`net_inc`		INT(8) NULL,
	`ev_bv`			FLOAT(12,8) NULL,
	`reinv`			INT(8) NULL,
	`ebit`			INT(8) NULL,
	`ev_cap`		FLOAT(12,8) NULL,
	`payout`		FLOAT(10,8) NULL,
	`hilo`			FLOAT(10,8) NULL,
	`sga`			INT(8) NULL,
	`ev`			FLOAT(10,2) NULL,
	`ncwc`			INT(8) NULL,
	PRIMARY KEY (symbol, quote_date))
ENGINE=InnoDB DEFAULT CHARSET=latin1